# Generated by Django 5.2.7 on 2025-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='documento_identidad',
            new_name='documento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('rnc', 'RNC'), ('otro', 'Otro')], max_length=20),
        ),
    ]
