# Generated by Django 5.2.7 on 2025-11-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_documento_identidad_cliente_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo_documento', models.CharField(blank=True, choices=[('rnc', 'RNC'), ('cedula', 'Cédula'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], max_length=20)),
                ('documento', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ('nombre',),
            },
        ),
    ]
