# Generated by Django 5.2.7 on 2025-11-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colores_disponibles',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
