# Generated by Django 5.2.7 on 2025-11-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='almacenamiento',
            field=models.CharField(blank=True, choices=[('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB'), ('64GB', '64 GB'), ('128GB', '128 GB'), ('256GB', '256 GB'), ('512GB', '512 GB'), ('1TB', '1 TB')], max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='memoria_ram',
            field=models.CharField(blank=True, choices=[('1GB', '1 GB'), ('2GB', '2 GB'), ('3GB', '3 GB'), ('4GB', '4 GB'), ('6GB', '6 GB'), ('8GB', '8 GB'), ('12GB', '12 GB'), ('16GB', '16 GB')], max_length=10),
        ),
    ]
