# Generated by Django 5.2.7 on 2025-11-05 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_remove_producto_tipo_producto_almacenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='ventas.impuesto'),
        ),
    ]
