# Generated by Django 5.2.7 on 2025-11-06 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_cashsession_venta_sesion_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
