# Generated by Django 5.2.7 on 2025-11-09 13:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_cashsession_total_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalVoucherConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre_contribuyente', models.CharField(blank=True, max_length=160)),
                ('rnc', models.CharField(blank=True, max_length=20, verbose_name='RNC')),
                ('correo_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=30)),
                ('tipo_por_defecto', models.CharField(blank=True, choices=[('CF1', 'CF1 - Crédito fiscal'), ('CF2', 'CF2 - Consumidor final'), ('CF3', 'CF3 - Regímenes especiales'), ('B14', 'B14 - Gastos menores'), ('B15', 'B15 - Regímenes especiales')], max_length=4)),
                ('serie_por_defecto', models.CharField(blank=True, max_length=10)),
                ('secuencia_siguiente', models.PositiveIntegerField(default=1)),
                ('dias_vencimiento', models.PositiveIntegerField(default=30)),
                ('emitir_automatico', models.BooleanField(default=False)),
                ('modo_pruebas', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de comprobante fiscal',
                'verbose_name_plural': 'Configuración de comprobante fiscal',
            },
        ),
        migrations.CreateModel(
            name='FiscalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('CF1', 'CF1 - Crédito fiscal'), ('CF2', 'CF2 - Consumidor final'), ('CF3', 'CF3 - Regímenes especiales'), ('B14', 'B14 - Gastos menores'), ('B15', 'B15 - Regímenes especiales')], max_length=4)),
                ('serie', models.CharField(max_length=10)),
                ('secuencia', models.PositiveIntegerField()),
                ('numero_completo', models.CharField(blank=True, max_length=32, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('itbis', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('otros_impuestos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto'), ('credito', 'Crédito')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('anulado', 'Anulado')], default='emitido', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_fiscal', to='ventas.venta')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='ventas.fiscalvoucherconfig')),
            ],
            options={
                'verbose_name': 'Comprobante fiscal',
                'verbose_name_plural': 'Comprobantes fiscales',
                'ordering': ('-fecha_emision', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FiscalVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('impuesto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_fiscales', to='ventas.producto')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.fiscalvoucher')),
            ],
            options={
                'verbose_name': 'Línea de comprobante fiscal',
                'verbose_name_plural': 'Líneas de comprobante fiscal',
                'ordering': ('voucher', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='fiscalvoucher',
            constraint=models.UniqueConstraint(fields=('serie', 'secuencia'), name='unique_fiscal_voucher_sequence'),
        ),
    ]
