# Generated by Django 5.2.7 on 2025-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_fiscalvoucherconfig_fiscalvoucher_fiscalvoucherline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalvoucher',
            name='cliente_documento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fiscalvoucher',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fiscalvoucher',
            name='correo_envio',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='fiscalvoucher',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
