# Generated by Django 5.2.7 on 2025-11-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_fiscalvoucher_cliente_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_auth_url',
            field=models.URLField(blank=True, verbose_name='URL autenticación'),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_base_url',
            field=models.URLField(blank=True, verbose_name='URL base API'),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_client_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_commercial_approval_url',
            field=models.URLField(blank=True, verbose_name='URL aprobación comercial'),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_directory_url',
            field=models.URLField(blank=True, verbose_name='URL directorio clientes'),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox / Pruebas'), ('production', 'Producción')], default='sandbox', max_length=20),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_status_url',
            field=models.URLField(blank=True, verbose_name='URL consulta estado'),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_submission_url',
            field=models.URLField(blank=True, verbose_name='URL recepción e-CF'),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='api_void_url',
            field=models.URLField(blank=True, verbose_name='URL anulación e-CF'),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='certificado_alias',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='certificado_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='certificado_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fiscalvoucherconfig',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fiscalvoucher',
            name='tipo',
            field=models.CharField(choices=[('B01', 'B01 - Crédito Fiscal'), ('CF2', 'CF2 - Consumidor final'), ('CF3', 'CF3 - Regímenes especiales'), ('B14', 'B14 - Gastos menores'), ('B15', 'B15 - Regímenes especiales')], max_length=4),
        ),
        migrations.AlterField(
            model_name='fiscalvoucherconfig',
            name='tipo_por_defecto',
            field=models.CharField(blank=True, choices=[('B01', 'B01 - Crédito Fiscal'), ('CF2', 'CF2 - Consumidor final'), ('CF3', 'CF3 - Regímenes especiales'), ('B14', 'B14 - Gastos menores'), ('B15', 'B15 - Regímenes especiales')], max_length=4),
        ),
    ]
