# Generated by Django 5.2.7 on 2025-11-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_fiscalvoucherconfig_api_auth_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalvoucher',
            name='dgii_enviado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalvoucher',
            name='dgii_estado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fiscalvoucher',
            name='dgii_respuesta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscalvoucher',
            name='dgii_track_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
