# Generated by Django 5.2.7 on 2025-11-10 01:06

import django.db.models.deletion
from django.db import migrations, models


def migrate_product_brands(apps, schema_editor):
    Producto = apps.get_model('ventas', 'Producto')
    Marca = apps.get_model('ventas', 'Marca')

    for producto in Producto.objects.all():
        raw_brand = getattr(producto, 'marca', None)
        if not raw_brand:
            if raw_brand not in (None, ''):
                producto.marca = ''
                producto.save(update_fields=['marca'])
            continue

        name = str(raw_brand).strip()
        if not name:
            producto.marca = ''
            producto.save(update_fields=['marca'])
            continue

        marca_obj = Marca.objects.filter(nombre__iexact=name).first()
        if not marca_obj:
            marca_obj = Marca.objects.create(nombre=name)

        producto.marca = str(marca_obj.pk)
        producto.save(update_fields=['marca'])


def revert_product_brands(apps, schema_editor):
    # No reverse action required; leave existing data untouched.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_marca'),
    ]

    operations = [
        migrations.RunPython(migrate_product_brands, revert_product_brands),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='ventas.marca'),
        ),
    ]
