# Generated by Django 5.2.7 on 2025-11-13 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0026_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacredito',
            name='abono_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cuentacredito',
            name='cuotas_pagadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuentacredito',
            name='frecuencia_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='cuentacredito',
            name='monto_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cuentacredito',
            name='numero_cuotas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
