# Generated by Django 5.2.7 on 2025-11-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_categoria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usar_impuesto_global',
            field=models.BooleanField(default=True, help_text='Si está habilitado, este producto usará la tasa global configurada.'),
        ),
    ]
