# Generated by Django 5.2.7 on 2025-11-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0032_producto_usar_impuesto_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Condición de producto',
                'verbose_name_plural': 'Condiciones de producto',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='tradeincredit',
            name='condiciones',
            field=models.ManyToManyField(blank=True, related_name='trade_in_creditos', to='ventas.productcondition'),
        ),
    ]
