# Generated by Django 5.2.7 on 2025-11-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0033_productcondition_tradeincredit_condiciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcondition',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='ProductoUnitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad_index', models.PositiveIntegerField()),
                ('imei', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_detalle', to='ventas.producto')),
            ],
            options={
                'verbose_name': 'Unidad de producto',
                'verbose_name_plural': 'Unidades de producto',
                'ordering': ('producto', 'unidad_index'),
                'unique_together': {('producto', 'unidad_index')},
            },
        ),
    ]
