# Generated by Django 5.2.7 on 2025-11-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_productounitdetail_almacenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productounitdetail',
            name='condicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_producto', to='ventas.productcondition'),
        ),
    ]
