# Generated by Cascade on 2025-11-22 13:25
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0036_productounitdetail_condicion"),
    ]

    operations = [
        migrations.AddField(
            model_name="productounitdetail",
            name="usar_impuesto_global",
            field=models.BooleanField(
                default=True,
                help_text="Si está habilitado, esta unidad usará la tasa global configurada.",
            ),
        ),
        migrations.AddField(
            model_name="productounitdetail",
            name="impuesto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="detalles_unidad",
                to="ventas.impuesto",
            ),
        ),
        migrations.AddField(
            model_name="detalleventa",
            name="unidad_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
