# Generated by Django 5.2.7 on 2025-11-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0038_productounitdetail_vida_bateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productounitdetail',
            name='codigo_barras',
            field=models.CharField(blank=True, editable=False, help_text='Código único generado automáticamente para escaneo con pistola', max_length=32, unique=True),
        ),
    ]
