# Generated by Django 5.2.7 on 2025-11-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0039_productounitdetail_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('phone', 'Teléfonos'), ('accessory', 'Accesorios'), ('laptop', 'Laptops'), ('tablet', 'Tablets'), ('gaming', 'Gaming')], default='phone', help_text='Tipo de producto que determina los campos específicos disponibles', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='almacenamiento',
            field=models.CharField(blank=True, choices=[('16GB', '16 GB'), ('32GB', '32 GB'), ('64GB', '64 GB'), ('128GB', '128 GB'), ('256GB', '256 GB'), ('512GB', '512 GB'), ('1TB', '1 TB')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productounitdetail',
            name='almacenamiento',
            field=models.CharField(blank=True, choices=[('16GB', '16 GB'), ('32GB', '32 GB'), ('64GB', '64 GB'), ('128GB', '128 GB'), ('256GB', '256 GB'), ('512GB', '512 GB'), ('1TB', '1 TB')], max_length=10),
        ),
        migrations.CreateModel(
            name='ProductoSpecificFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procesador', models.CharField(blank=True, help_text='Procesador del dispositivo', max_length=100)),
                ('pantalla', models.CharField(blank=True, help_text='Tamaño y tipo de pantalla', max_length=100)),
                ('sistema_operativo', models.CharField(blank=True, help_text='Sistema operativo', max_length=50)),
                ('tipo_accesorio', models.CharField(blank=True, help_text='Tipo específico de accesorio', max_length=50)),
                ('compatibilidad', models.CharField(blank=True, help_text='Dispositivos compatibles', max_length=200)),
                ('material', models.CharField(blank=True, help_text='Material del producto', max_length=50)),
                ('potencia', models.CharField(blank=True, help_text='Potencia o capacidad', max_length=50)),
                ('tarjeta_grafica', models.CharField(blank=True, help_text='Tarjeta gráfica', max_length=100)),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie', max_length=100)),
                ('tipo_gaming', models.CharField(blank=True, help_text='Tipo de producto gaming', max_length=50)),
                ('plataforma', models.CharField(blank=True, help_text='Plataforma de gaming', max_length=50)),
                ('conectividad', models.CharField(blank=True, help_text='Tipo de conectividad', max_length=50)),
                ('extra_fields', models.JSONField(blank=True, default=dict, help_text='Campos adicionales específicos')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specific_fields', to='ventas.producto')),
            ],
            options={
                'verbose_name': 'Campos específicos del producto',
                'verbose_name_plural': 'Campos específicos de productos',
            },
        ),
    ]
