# Generated by Django 5.2.7 on 2025-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0040_add_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('phone', 'Teléfonos'), ('accessory', 'Accesorios'), ('laptop', 'Laptops'), ('tablet', 'Tablets'), ('gaming', 'Gaming')], help_text='Tipo de producto al que pertenece esta categoría', max_length=20, null=True),
        ),
    ]
