# Generated by Django 5.2.7 on 2025-11-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0041_add_categoria_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productounitdetail',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra específico para esta unidad', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productounitdetail',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta específico para esta unidad', max_digits=10, null=True),
        ),
    ]
