# Generated by Django 5.2.7 on 2025-11-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0042_add_precio_to_unit_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icono', models.CharField(choices=[('phone', '📱 Teléfono'), ('accessory', '🔌 Accesorio'), ('laptop', '💻 Laptop'), ('tablet', '📟 Tablet'), ('gaming', '🎮 Gaming'), ('watch', '⌚ Reloj'), ('headphones', '🎧 Auriculares'), ('camera', '📷 Cámara'), ('speaker', '🔊 Altavoz'), ('other', '📦 Otro'), ('custom', '🔧 Personalizado')], default='custom', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Producto',
                'ordering': ['nombre'],
            },
        ),
    ]
