# Generated by Django 5.2.7 on 2025-11-26 13:48

from django.db import migrations, models
import django.db.models.deletion


def create_tipos_producto_base(apps, schema_editor):
    """Crear tipos de producto base si no existen"""
    TipoProducto = apps.get_model('ventas', 'TipoProducto')
    
    tipos_base = [
        ('phone', 'Teléfonos'),
        ('accessory', 'Accesorios'),
        ('laptop', 'Laptops'),
        ('tablet', 'Tablets'),
        ('gaming', 'Gaming'),
    ]
    
    for slug, nombre in tipos_base:
        TipoProducto.objects.get_or_create(
            slug=slug,
            defaults={
                'nombre': nombre,
                'icono': slug,
                'activo': True
            }
        )


def migrate_categoria_tipo_producto_data(apps, schema_editor):
    """Migrar datos de categorías al nuevo formato ForeignKey"""
    Categoria = apps.get_model('ventas', 'Categoria')
    TipoProducto = apps.get_model('ventas', 'TipoProducto')
    
    # Mapeo de valores antiguos a nuevos tipos de producto
    mapeo = {
        'phone': 'phone',
        'accessory': 'accessory',
        'laptop': 'laptop',
        'tablet': 'tablet',
        'gaming': 'gaming',
    }
    
    for categoria in Categoria.objects.all():
        if categoria.tipo_producto and categoria.tipo_producto in mapeo:
            try:
                tipo_producto = TipoProducto.objects.get(slug=mapeo[categoria.tipo_producto])
                categoria.tipo_producto_id = tipo_producto.id
                categoria.save(update_fields=['tipo_producto'])
            except TipoProducto.DoesNotExist:
                # Si no existe el tipo, dejar como null
                categoria.tipo_producto = None
                categoria.save(update_fields=['tipo_producto'])


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0043_add_tipo_producto_model'),
    ]

    operations = [
        # Primero crear los tipos de producto base
        migrations.RunPython(create_tipos_producto_base),
        
        # Luego migrar los datos
        migrations.RunPython(migrate_categoria_tipo_producto_data),
        
        # Finalmente aplicar el cambio de campo
        migrations.AlterField(
            model_name='categoria',
            name='tipo_producto',
            field=models.ForeignKey(
                blank=True, 
                help_text='Tipo de producto al que pertenece esta categoría', 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                to='ventas.tipoproducto'
            ),
        ),
    ]
