# Generated by Django 5.2.7 on 2025-11-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0045_migrate_categoria_tipo_producto_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='productounitdetail',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se vendió esta unidad', null=True),
        ),
        migrations.AddField(
            model_name='productounitdetail',
            name='vendido',
            field=models.BooleanField(default=False, help_text='Indica si esta unidad ha sido vendida'),
        ),
    ]
