# Generated by Django 5.2.7 on 2025-11-27 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0046_productounitdetail_fecha_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de compra del producto', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta del producto', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
