# Generated by Django 5.2.7 on 2025-11-03 12:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio de reparación',
                'verbose_name_plural': 'Servicios de reparación',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('imei', models.CharField(blank=True, max_length=20, verbose_name='IMEI')),
                ('problema_reportado', models.TextField()),
                ('diagnostico_preliminar', models.TextField(blank=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('diagnosticada', 'Diagnosticada'), ('en_reparacion', 'En reparación'), ('lista', 'Lista para entrega'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='recibida', max_length=20)),
                ('fecha_prometida', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='ventas.cliente')),
                ('dispositivo', models.ForeignKey(blank=True, help_text='Seleccione un producto si forma parte del inventario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones', to='ventas.producto')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reparación',
                'verbose_name_plural': 'Reparaciones',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BitacoraReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('diagnosticada', 'Diagnosticada'), ('en_reparacion', 'En reparación'), ('lista', 'Lista para entrega'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_reparacion', to=settings.AUTH_USER_MODEL)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='reparaciones.reparacion')),
            ],
            options={
                'verbose_name': 'Evento de reparación',
                'verbose_name_plural': 'Eventos de reparación',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReparacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('metodo_pago', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('comentarios', models.TextField(blank=True)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reparaciones.reparacion')),
            ],
            options={
                'verbose_name': 'Pago de reparación',
                'verbose_name_plural': 'Pagos de reparación',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReparacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='reparaciones.reparacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='reparaciones.servicioreparacion')),
            ],
            options={
                'verbose_name': 'Servicio aplicado',
                'verbose_name_plural': 'Servicios aplicados',
                'ordering': ('reparacion', 'servicio'),
            },
        ),
    ]
