# Generated by Django 5.2.7 on 2025-11-20 14:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_siteconfiguration_global_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='global_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
