# Generated by Django 5.2.7 on 2025-11-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_siteconfiguration_global_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='empresa_direccion',
            field=models.TextField(default='Dirección por defecto'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='empresa_nombre',
            field=models.CharField(default='Sistema POS', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='empresa_rnc',
            field=models.CharField(default='123456789', max_length=15),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='empresa_telefono',
            field=models.CharField(default='809-555-1234', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_formato',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_incluir_itbis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_incluir_leyendas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_incluir_logo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_incluir_pie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_info_adicional',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_posicion_logo',
            field=models.CharField(default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_resolucion',
            field=models.CharField(default='RES-123456789', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_secuencia_inicial',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_serie',
            field=models.CharField(default='A0101', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_tamano_logo',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='factura_tipo_comprobante',
            field=models.CharField(default='01', max_length=2),
        ),
    ]
