# Generated by Django 5.2.7 on 2025-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_siteconfiguration_empresa_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='alerta_stock_bajo_porcentaje',
            field=models.PositiveIntegerField(default=20, help_text='Porcentaje para alerta de stock bajo'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='bloquear_venta_sin_stock',
            field=models.BooleanField(default=False, help_text='Bloquear ventas cuando no hay stock disponible'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stock_minimo_default',
            field=models.PositiveIntegerField(default=5, help_text='Stock mínimo por defecto para nuevos productos'),
        ),
    ]
